### ISSUE TITLE
URGENT: Unable to find dialog with real id

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#22]
When we launch a ChatActivity with a valid dialogId in the intent extra, we get an error message that says "Unable to find dialog with id: <dialog id>".  Whats extra strange is that if a message is sent to that dialog, the message itself shows up in the chat behind that error message. It seems that the AF DialogService is not finding the dialog, although maybe the ChatService is able to find it, so the messages come in. This seems to happen regardless of whether the dialog is 1-1 or a group dialog.

**Comment by nrschultz** [comment]
![image](https://cloud.githubusercontent.com/assets/463157/22482314/70f43286-e7c6-11e6-8213-82e134d50666.png)

**Comment by laeroah** [comment]
Please provide the following:
1. app id
2. the user id of the user who's requesting this dialog
3. the dialog id
You could also double check if the user is actually in the dialog.

**Comment by nrschultz** [comment]
AppId: `QVdG4xshxzgb7EWouxMfowtt`
User ID: `50aa786aec06a51a0691f573` (that is the user logged into the app when I see this error)
Dialog ID: `e7efa20c-e5e9-43c1-a353-ebf4851ee828` (copied from that screenshot, although this same issue happens with any new dialog id)


Sorry, I just realized that I didn't give full context around this error.  This happens when we're deep linking into the app from a dialog invite push notification.  This dialog was just created by a user on a iOS device, including this android user (id above).  When the push notification is open, we launch a ChatActivity with an Intent that has the above dialogID available on it, but during the onCreate of the ChatActivity (and by extension, the DialogActivity that it subclasses) we get this error.

**Comment by laeroah** [comment]
it will be updated in the next build to handle this

**Comment by hagitmer** [comment]
@laeroah this still happens with 3.0.9 for 1:1 conversations.

**Comment by hagitmer** [comment]
@laeroah the same issue happened on iOS. Any idea if that was fixed or should I open a new Github issue for iOS?

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#22
